### ISSUE TITLE
Path to fwhem remote not uptodate.

### ISSUE THREAD

**Issue by maedot-d** [aospfhem/noobbuilds_manifest#1]
Hi,

It seems you have forgotten to update the path when you moved your project.

**Comment by fwhem** [comment]
Thanks for the heads up. Should be good now. I never tested/looked after I moved it. Just plan missed it. Thanks again.

**Comment by maedot-d** [comment]
I have a side question regarding custom rom from source.
I need to build my own for samsung S7, and have got all files (kernel, device, vendor) from other developers' git repos. My main objective is to recompile netd only. But the problem I keep bumping into is that, the newly compile binary has almost half the size of the original one I get from the phone and most of all does not work. Do you have any idea where I should be looking to fix this?

**Comment by fwhem** [comment]
Sorry. I know nothing about building Samsung from source --They very, very diff animals.

**Comment by maedot-d** [comment]
thanks for the honest reply!
